name: Daily Run

on:
  schedule:
    # Runs every day at noon CST
    - cron: '0 18 * * *'

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run main.py
        run: python main.py
        env:
          AZURE_SQL_DATABASE: ${{ secrets.AZURE_SQL_DATABASE }}
          AZURE_SQL_ENCRYPT: ${{ secrets.AZURE_SQL_ENCRYPT }}
          AZURE_SQL_PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}
          AZURE_SQL_SCHEMA: ${{ secrets.AZURE_SQL_SCHEMA }}
          AZURE_SQL_SERVER: ${{ secrets.AZURE_SQL_SERVER }}
          AZURE_SQL_TIMEOUT: ${{ secrets.AZURE_SQL_TIMEOUT }}
          AZURE_SQL_TRUST_SERVER_CERTIFICATE: ${{ secrets.AZURE_SQL_TRUST_SERVER_CERTIFICATE }}
          AZURE_SQL_USER: ${{ secrets.AZURE_SQL_USER }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_USER: ${{ secrets.SMTP_USER }}